In [ ]:
### 1st API

In [121]:
import requests
import json

response = requests.get('https://api.spaceflightnewsapi.net/v3/articles')

response.json()

results = response.json()
results

[{'id': 16813,
  'title': 'Space companies face difficult investment environment',
  'url': 'https://spacenews.com/space-companies-face-difficult-investment-environment/',
  'imageUrl': 'https://spacenews.com/wp-content/uploads/2022/09/im1lander-2022.jpg',
  'newsSite': 'SpaceNews',
  'summary': 'Rising interest rates are making it more difficult for space startups to raise money, some warn, forcing them to seek alternative sources of funding.',
  'publishedAt': '2022-10-11T12:10:25.000Z',
  'updatedAt': '2022-10-11T12:10:25.238Z',
  'featured': False,
  'launches': [],
  'events': []},
 {'id': 16809,
  'title': 'SpaceX deploys two of six C-band satellites Intelsat is launching this year',
  'url': 'https://spacenews.com/spacex-deploys-two-of-six-c-band-satellites-intelsat-is-launching-this-year/',
  'imageUrl': 'https://spacenews.com/wp-content/uploads/2022/10/hereSpaceX-intelsat-launch.jpeg',
  'newsSite': 'SpaceNews',
  'summary': 'SpaceX Oct. 8 successfully deployed the first two of seven satellites Intelsat needs to clear C-band spectrum in the United States, keeping the operator on course to launch all but one of them before the end of this year.',
  'publishedAt': '2022-10-10T17:10:15.000Z',
  'updatedAt': '2022-10-11T06:50:41.636Z',
  'featured': False,
  'launches': [{'id': '03ee73b8-a553-4575-8dfa-d0da4e7939e9',
    'provider': 'Launch Library 2'}],
  'events': []},
 {'id': 16808,
  'title': 'Former SES CEO joins megaconstellation startup E-Space',
  'url': 'https://spacenews.com/former-ses-ceo-joins-megaconstellation-startup-e-space/',
  'imageUrl': 'https://spacenews.com/wp-content/uploads/2022/08/New-Los-Gatos-Office-June-2022.jpg',
  'newsSite': 'SpaceNews',
  'summary': 'Former SES CEO Karim Michel Sabbagh has returned to the space industry to oversee strategy in Europe and the Middle East for E-Space, the connectivity startup plotting a network of hundreds of thousands of satellites.',
  'publishedAt': '2022-10-10T16:00:15.000Z',
  'updatedAt': '2022-10-10T16:00:15.522Z',
  'featured': False,
  'launches': [],
  'events': []},
 {'id': 16807,
  'title': 'Launch on demand: If satellites are shot down, will Space Force be ready to restock?',
  'url': 'https://spacenews.com/launch-on-demand-if-satellites-are-shot-down-will-space-force-be-ready-to-restock/',
  'imageUrl': 'https://spacenews.com/wp-content/uploads/2022/10/above-the-clouds-2.jpg',
  'newsSite': 'SpaceNews',
  'summary': 'Responsive space launch capabilities are gaining more attention as world events that underline the strategic value of satellites also makes them more attractive targets for adversaries.',
  'publishedAt': '2022-10-10T14:10:11.000Z',
  'updatedAt': '2022-10-10T14:10:11.432Z',
  'featured': False,
  'launches': [],
  'events': []},
 {'id': 16812,
  'title': "United Launch Alliance's debut Vulcan mission slips to 2023 -CEO",
  'url': 'https://www.reuters.com/lifestyle/science/united-launch-alliances-debut-vulcan-mission-slips-2023-ceo-2022-10-10/',
  'imageUrl': 'https://www.reuters.com/resizer/8Z_6fOnIMNDHUzMf0PPd6umXt08=/1200x0/filters:quality(80)/cloudfront-us-east-2.images.arcpublishing.com/reuters/HNVITNELYBKR7PT3KUTBCUTBKY.jpg',
  'newsSite': 'Reuters',
  'summary': "United Launch Alliance has pushed the debut launch of its new Vulcan rocket to early 2023 at the request of one of its customers, the company's chief executive said, further delaying a benchmark mission crucial to the Boeing-Lockheed joint venture's launch business.",
  'publishedAt': '2022-10-10T12:32:00.000Z',
  'updatedAt': '2022-10-11T07:44:00.183Z',
  'featured': False,
  'launches': [{'id': 'b973e965-3901-4bda-9236-b0afee33f388',
    'provider': 'Launch Library 2'}],
  'events': []},
 {'id': 16806,
  'title': 'Stoke Space aims to build rapidly reusable rocket with a completely novel design',
  'url': 'https://arstechnica.com/science/2022/10/stoke-space-aims-to-build-rapidly-reusable-rocket-with-a-completely-novel-design/',
  'imageUrl': 'https://cdn.arstechnica.net/wp-content/uploads/2022/10/stoke1.jpg',
  'newsSite': 'Arstechnica',
  'summary': '"We took a leap of faith and jumped off a cliff."',
  'publishedAt': '2022-10-10T11:30:36.000Z',
  'updatedAt': '2022-10-10T11:40:23.303Z',
  'featured': False,
  'launches': [],
  'events': []},
 {'id': 16805,
  'title': 'Firefly says Alpha launch a success despite payload reentries',
  'url': 'https://spacenews.com/firefly-says-alpha-launch-a-success-despite-payload-reentries/',
  'imageUrl': 'https://spacenews.com/wp-content/uploads/2022/10/alpha-totheback-launch.jpg',
  'newsSite': 'SpaceNews',
  'summary': 'Firefly Aerospace says its Alpha launch early this month was a success despite the fact that its payloads, placed in a lower orbit than planned, reentered within several days.',
  'publishedAt': '2022-10-10T11:30:19.000Z',
  'updatedAt': '2022-10-10T19:17:23.514Z',
  'featured': False,
  'launches': [{'id': 'a7fcb777-83a4-4876-951b-ac31a9d37252',
    'provider': 'Launch Library 2'}],
  'events': []},
 {'id': 16811,
  'title': 'SpaceX’s first Falcon Heavy launch in three years eyes late-October liftoff',
  'url': 'https://www.teslarati.com/spacex-falcon-heavy-rocket-first-launch-three-years-take-two/',
  'imageUrl': 'https://www.teslarati.com/wp-content/uploads/2019/04/Falcon-Heavy-Flight-2-B1052-B1053-B1055-integration-SpaceX-full-res-1-crop-c.jpg',
  'newsSite': 'Teslarati',
  'summary': 'For the second time in 2022, SpaceX’s Falcon Heavy rocket has a firm launch date for the first time in more than...',
  'publishedAt': '2022-10-10T05:00:40.000Z',
  'updatedAt': '2022-10-11T06:50:56.262Z',
  'featured': False,
  'launches': [{'id': 'aa88b853-9e04-4a28-9433-d87799331b1b',
    'provider': 'Launch Library 2'}],
  'events': []},
 {'id': 16810,
  'title': 'Starlink now available in Japan',
  'url': 'https://www.teslarati.com/starlink-now-available-in-japan/',
  'imageUrl': 'https://www.teslarati.com/wp-content/uploads/2022/10/Starlink-now-available-in-Japan.jpeg',
  'newsSite': 'Teslarati',
  'summary': 'Starlink is now available in Japan, SpaceX announced Monday, adding that Japan is the first Asian country to access Starlink. In September...',
  'publishedAt': '2022-10-10T00:50:43.000Z',
  'updatedAt': '2022-10-11T00:50:53.397Z',
  'featured': False,
  'launches': [],
  'events': []},
 {'id': 16803,
  'title': 'Researchers discover galactic shield of gas surrounding the Magellanic Cloud galaxies',
  'url': 'https://www.nasaspaceflight.com/2022/10/magellanic-clouds-corona/',
  'imageUrl': 'https://www.nasaspaceflight.com/wp-content/uploads/2022/10/STScI-01GDXBAE4YNC1YR6M1Z5XH1BTH-1170x658.png',
  'newsSite': 'NASASpaceflight',
  'summary': 'The largest satellite galaxies of the Milky Way — the Large and Small Magellanic Clouds — have been undergoing a treacherous interaction for billions of years. As the galactic pair are pulled toward the Milky Way, they are constantly orbiting each other and unraveling themselves, creating massive trails of gaseous debris. Yet, the galaxies have remained intact and continue to host star formation inside of them — something that has puzzled astronomers and physicists for years.',
  'publishedAt': '2022-10-09T16:55:45.000Z',
  'updatedAt': '2022-10-09T17:00:43.951Z',
  'featured': False,
  'launches': [],
  'events': []}]

In [122]:
import pandas as pd
pd.set_option("display.max_rows", 0)

data = pd.DataFrame(results)
print(data.shape)
data.head(10)

(10, 11)

,id,title,url,imageUrl,newsSite,summary,publishedAt,updatedAt,featured,launches,events
0,16813,Space companies face difficult investment envi...,https://spacenews.com/space-companies-face-dif...,https://spacenews.com/wp-content/uploads/2022/...,SpaceNews,Rising interest rates are making it more diffi...,2022-10-11T12:10:25.000Z,2022-10-11T12:10:25.238Z,False,[],[]
1,16809,SpaceX deploys two of six C-band satellites In...,https://spacenews.com/spacex-deploys-two-of-si...,https://spacenews.com/wp-content/uploads/2022/...,SpaceNews,SpaceX Oct. 8 successfully deployed the first ...,2022-10-10T17:10:15.000Z,2022-10-11T06:50:41.636Z,False,[{'id': '03ee73b8-a553-4575-8dfa-d0da4e7939e9'...,[]
2,16808,Former SES CEO joins megaconstellation startup...,https://spacenews.com/former-ses-ceo-joins-meg...,https://spacenews.com/wp-content/uploads/2022/...,SpaceNews,Former SES CEO Karim Michel Sabbagh has return...,2022-10-10T16:00:15.000Z,2022-10-10T16:00:15.522Z,False,[],[]
3,16807,"Launch on demand: If satellites are shot down,...",https://spacenews.com/launch-on-demand-if-sate...,https://spacenews.com/wp-content/uploads/2022/...,SpaceNews,Responsive space launch capabilities are gaini...,2022-10-10T14:10:11.000Z,2022-10-10T14:10:11.432Z,False,[],[]
4,16812,United Launch Alliance's debut Vulcan mission ...,https://www.reuters.com/lifestyle/science/unit...,https://www.reuters.com/resizer/8Z_6fOnIMNDHUz...,Reuters,United Launch Alliance has pushed the debut la...,2022-10-10T12:32:00.000Z,2022-10-11T07:44:00.183Z,False,[{'id': 'b973e965-3901-4bda-9236-b0afee33f388'...,[]
5,16806,Stoke Space aims to build rapidly reusable roc...,https://arstechnica.com/science/2022/10/stoke-...,https://cdn.arstechnica.net/wp-content/uploads...,Arstechnica,"""We took a leap of faith and jumped off a cliff.""",2022-10-10T11:30:36.000Z,2022-10-10T11:40:23.303Z,False,[],[]
6,16805,Firefly says Alpha launch a success despite pa...,https://spacenews.com/firefly-says-alpha-launc...,https://spacenews.com/wp-content/uploads/2022/...,SpaceNews,Firefly Aerospace says its Alpha launch early ...,2022-10-10T11:30:19.000Z,2022-10-10T19:17:23.514Z,False,[{'id': 'a7fcb777-83a4-4876-951b-ac31a9d37252'...,[]
7,16811,SpaceX’s first Falcon Heavy launch in three ye...,https://www.teslarati.com/spacex-falcon-heavy-...,https://www.teslarati.com/wp-content/uploads/2...,Teslarati,"For the second time in 2022, SpaceX’s Falcon H...",2022-10-10T05:00:40.000Z,2022-10-11T06:50:56.262Z,False,[{'id': 'aa88b853-9e04-4a28-9433-d87799331b1b'...,[]
8,16810,Starlink now available in Japan,https://www.teslarati.com/starlink-now-availab...,https://www.teslarati.com/wp-content/uploads/2...,Teslarati,"Starlink is now available in Japan, SpaceX ann...",2022-10-10T00:50:43.000Z,2022-10-11T00:50:53.397Z,False,[],[]
9,16803,Researchers discover galactic shield of gas su...,https://www.nasaspaceflight.com/2022/10/magell...,https://www.nasaspaceflight.com/wp-content/upl...,NASASpaceflight,The largest satellite galaxies of the Milky Wa...,2022-10-09T16:55:45.000Z,2022-10-09T17:00:43.951Z,False,[],[]

In [123]:
from pandas.io.json import json_normalize

flattened_data = json_normalize(results)
print(flattened_data.shape)
flattened_data

(10, 11)

/var/folders/r5/f_ppj8yd0_bfvgt7j7sddzzh0000gn/T/ipykernel_1268/2480666601.py:3: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  flattened_data = json_normalize(results)

,id,title,url,imageUrl,newsSite,summary,publishedAt,updatedAt,featured,launches,events
0,16813,Space companies face difficult investment envi...,https://spacenews.com/space-companies-face-dif...,https://spacenews.com/wp-content/uploads/2022/...,SpaceNews,Rising interest rates are making it more diffi...,2022-10-11T12:10:25.000Z,2022-10-11T12:10:25.238Z,False,[],[]
1,16809,SpaceX deploys two of six C-band satellites In...,https://spacenews.com/spacex-deploys-two-of-si...,https://spacenews.com/wp-content/uploads/2022/...,SpaceNews,SpaceX Oct. 8 successfully deployed the first ...,2022-10-10T17:10:15.000Z,2022-10-11T06:50:41.636Z,False,[{'id': '03ee73b8-a553-4575-8dfa-d0da4e7939e9'...,[]
2,16808,Former SES CEO joins megaconstellation startup...,https://spacenews.com/former-ses-ceo-joins-meg...,https://spacenews.com/wp-content/uploads/2022/...,SpaceNews,Former SES CEO Karim Michel Sabbagh has return...,2022-10-10T16:00:15.000Z,2022-10-10T16:00:15.522Z,False,[],[]
3,16807,"Launch on demand: If satellites are shot down,...",https://spacenews.com/launch-on-demand-if-sate...,https://spacenews.com/wp-content/uploads/2022/...,SpaceNews,Responsive space launch capabilities are gaini...,2022-10-10T14:10:11.000Z,2022-10-10T14:10:11.432Z,False,[],[]
4,16812,United Launch Alliance's debut Vulcan mission ...,https://www.reuters.com/lifestyle/science/unit...,https://www.reuters.com/resizer/8Z_6fOnIMNDHUz...,Reuters,United Launch Alliance has pushed the debut la...,2022-10-10T12:32:00.000Z,2022-10-11T07:44:00.183Z,False,[{'id': 'b973e965-3901-4bda-9236-b0afee33f388'...,[]
5,16806,Stoke Space aims to build rapidly reusable roc...,https://arstechnica.com/science/2022/10/stoke-...,https://cdn.arstechnica.net/wp-content/uploads...,Arstechnica,"""We took a leap of faith and jumped off a cliff.""",2022-10-10T11:30:36.000Z,2022-10-10T11:40:23.303Z,False,[],[]
6,16805,Firefly says Alpha launch a success despite pa...,https://spacenews.com/firefly-says-alpha-launc...,https://spacenews.com/wp-content/uploads/2022/...,SpaceNews,Firefly Aerospace says its Alpha launch early ...,2022-10-10T11:30:19.000Z,2022-10-10T19:17:23.514Z,False,[{'id': 'a7fcb777-83a4-4876-951b-ac31a9d37252'...,[]
7,16811,SpaceX’s first Falcon Heavy launch in three ye...,https://www.teslarati.com/spacex-falcon-heavy-...,https://www.teslarati.com/wp-content/uploads/2...,Teslarati,"For the second time in 2022, SpaceX’s Falcon H...",2022-10-10T05:00:40.000Z,2022-10-11T06:50:56.262Z,False,[{'id': 'aa88b853-9e04-4a28-9433-d87799331b1b'...,[]
8,16810,Starlink now available in Japan,https://www.teslarati.com/starlink-now-availab...,https://www.teslarati.com/wp-content/uploads/2...,Teslarati,"Starlink is now available in Japan, SpaceX ann...",2022-10-10T00:50:43.000Z,2022-10-11T00:50:53.397Z,False,[],[]
9,16803,Researchers discover galactic shield of gas su...,https://www.nasaspaceflight.com/2022/10/magell...,https://www.nasaspaceflight.com/wp-content/upl...,NASASpaceflight,The largest satellite galaxies of the Milky Wa...,2022-10-09T16:55:45.000Z,2022-10-09T17:00:43.951Z,False,[],[]

In [112]:
### 2 API

In [91]:
import requests
import json

response1 = requests.get('https://quote-garden.herokuapp.com/api/v3/quotes')

response1
results1 = response1.json()
#print(results1)
results1['data'] # when i print the results1 it gives the actual responses are available only in the data key of the response object so i just picked the data.

[{'_id': '5eb17aadb69dc744b4e70d2e',
  'quoteText': 'All diseases run into one, old age.',
  'quoteAuthor': 'Ralph Waldo Emerson',
  'quoteGenre': 'age',
  '__v': 0},
 {'_id': '5eb17aadb69dc744b4e70d36',
  'quoteText': 'Alas, after a certain age every man is responsible for his face.',
  'quoteAuthor': 'Albert Camus',
  'quoteGenre': 'age',
  '__v': 0},
 {'_id': '5eb17aadb69dc744b4e70d44',
  'quoteText': 'When grace is joined with wrinkles, it is adorable. There is an unspeakable dawn in happy old age.',
  'quoteAuthor': 'Victor Hugo',
  'quoteGenre': 'age',
  '__v': 0},
 {'_id': '5eb17aadb69dc744b4e70d48',
  'quoteText': 'Age is not a particularly interesting subject. Anyone can get old. All you have to do is live long enough.',
  'quoteAuthor': 'Don Marquis',
  'quoteGenre': 'age',
  '__v': 0},
 {'_id': '5eb17aadb69dc744b4e70d5e',
  'quoteText': 'My notion of a wife at 40 is that a man should be able to change her, like a bank note, for two 20s.',
  'quoteAuthor': 'Warren Beatty',
  'quoteGenre': 'age',
  '__v': 0},
 {'_id': '5eb17aadb69dc744b4e70d65',
  'quoteText': 'Aging seems to be the only available way to live a long life.',
  'quoteAuthor': "Kitty O'Neill Collins",
  'quoteGenre': 'age',
  '__v': 0},
 {'_id': '5eb17aadb69dc744b4e70d6b',
  'quoteText': "You know you're getting old when all the names in your black book have M. D. after them.",
  'quoteAuthor': 'Harrison Ford',
  'quoteGenre': 'age',
  '__v': 0},
 {'_id': '5eb17aadb69dc744b4e70d78',
  'quoteText': 'Middle age is youth without levity, and age without decay.',
  'quoteAuthor': 'Doris Day',
  'quoteGenre': 'age',
  '__v': 0},
 {'_id': '5eb17aadb69dc744b4e70d7d',
  'quoteText': "The answer to old age is to keep one's mind busy and to go on with one's life as if it were interminable. I always admired Chekhov for building a new house when he was dying of tuberculosis.",
  'quoteAuthor': 'Leon Edel',
  'quoteGenre': 'age',
  '__v': 0},
 {'_id': '5eb17aadb69dc744b4e70d86',
  'quoteText': 'Those who love deeply never grow old they may die of old age, but they die young.',
  'quoteAuthor': 'Dorothy Canfield Fisher',
  'quoteGenre': 'age',
  '__v': 0}]

In [93]:
import pandas as pd
pd.set_option("display.max_rows", 0)

data1 = pd.DataFrame(results1['data'])
print(data1.shape)
data1.head(10)

(10, 5)

,_id,quoteText,quoteAuthor,quoteGenre,__v
0,5eb17aadb69dc744b4e70d2e,"All diseases run into one, old age.",Ralph Waldo Emerson,age,0
1,5eb17aadb69dc744b4e70d36,"Alas, after a certain age every man is respons...",Albert Camus,age,0
2,5eb17aadb69dc744b4e70d44,"When grace is joined with wrinkles, it is ador...",Victor Hugo,age,0
3,5eb17aadb69dc744b4e70d48,Age is not a particularly interesting subject....,Don Marquis,age,0
4,5eb17aadb69dc744b4e70d5e,My notion of a wife at 40 is that a man should...,Warren Beatty,age,0
5,5eb17aadb69dc744b4e70d65,Aging seems to be the only available way to li...,Kitty O'Neill Collins,age,0
6,5eb17aadb69dc744b4e70d6b,You know you're getting old when all the names...,Harrison Ford,age,0
7,5eb17aadb69dc744b4e70d78,"Middle age is youth without levity, and age wi...",Doris Day,age,0
8,5eb17aadb69dc744b4e70d7d,The answer to old age is to keep one's mind bu...,Leon Edel,age,0
9,5eb17aadb69dc744b4e70d86,Those who love deeply never grow old they may ...,Dorothy Canfield Fisher,age,0

In [120]:
from pandas.io.json import json_normalize

flattened_data1 = json_normalize(results1['data'])
print(flattened_data1.shape)
flattened_data1

(10, 5)

/var/folders/r5/f_ppj8yd0_bfvgt7j7sddzzh0000gn/T/ipykernel_1268/1909536014.py:3: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  flattened_data1 = json_normalize(results1['data'])

,_id,quoteText,quoteAuthor,quoteGenre,__v
0,5eb17aadb69dc744b4e70d2e,"All diseases run into one, old age.",Ralph Waldo Emerson,age,0
1,5eb17aadb69dc744b4e70d36,"Alas, after a certain age every man is respons...",Albert Camus,age,0
2,5eb17aadb69dc744b4e70d44,"When grace is joined with wrinkles, it is ador...",Victor Hugo,age,0
3,5eb17aadb69dc744b4e70d48,Age is not a particularly interesting subject....,Don Marquis,age,0
4,5eb17aadb69dc744b4e70d5e,My notion of a wife at 40 is that a man should...,Warren Beatty,age,0
5,5eb17aadb69dc744b4e70d65,Aging seems to be the only available way to li...,Kitty O'Neill Collins,age,0
6,5eb17aadb69dc744b4e70d6b,You know you're getting old when all the names...,Harrison Ford,age,0
7,5eb17aadb69dc744b4e70d78,"Middle age is youth without levity, and age wi...",Doris Day,age,0
8,5eb17aadb69dc744b4e70d7d,The answer to old age is to keep one's mind bu...,Leon Edel,age,0
9,5eb17aadb69dc744b4e70d86,Those who love deeply never grow old they may ...,Dorothy Canfield Fisher,age,0

In [ ]:
### 3. API tried with the keys

In [124]:
import getpass
apikey = getpass.getpass()

········

In [129]:
response2 = requests.get('https://phonevalidation.abstractapi.com/v1?api_key=' + apikey + '&phone=31626317687')  
    

#response
results2 = response2.json()
results2

{'phone': '31626317687',
 'valid': True,
 'format': {'international': '+31626317687', 'local': '06 26317687'},
 'country': {'code': 'NL', 'name': 'Netherlands', 'prefix': '+31'},
 'location': 'Netherlands',
 'type': 'mobile',
 'carrier': 'Telfort'}

In [131]:
print(results2['country']['name'])

Netherlands